### ISSUE TITLE
US01 - Fazer login no sistema

### ISSUE THREAD

**Issue by saracampss** [fga-eps-mds/2024.1-SENTINELA-DOC#11]
### Descrição 
Eu como USUÁRIOS (administrador, gestor, advogado, sindicalizado) dado que já foi confirmado o email e senha gostaria de fazer login no sistema para acessar a minha conta.

#### Interface
- [x] Campos obrigatórios: Email, senha
- [x] Apresentar erro de login em caso de campo (email/senha) não preenchido
- [x] Apresentar erro de login em caso de campo (email/senha) preenchido com valores errados
- [x] O campo email deve seguir o formato de email padrão (e.g., usuario@dominio.com);
- [x] O campo email deve conter um caractere "@" e um domínio válido (e.g., .com, .org, .net, etc.);
- [x] Se as credenciais forem válidas, o usuário deve ser autenticado (geração de token) e redirecionado para a página inicial 
- [x] Permitir usuário alterar senha em caso de esquecimento 
- [x] Usuário deve receber email conforme protótipo com link para geração de nova senha 
- [x] A senha deve ser alterada no banco após gerar nova senha

### Tarefas
- [x] Criar protótipo da tela 
- [x] Enviar protótipo para validação do cliente
- [ ] Gerar código fonte responsivo conforme protótipo e critérios de aceitação
- [ ] Testes 

### Protótipo
https://www.figma.com/proto/kJgE4ThZiTpMIufCMTbbCI/Prot%C3%B3tipos?page-id=0%3A1&node-id=2-6196&viewport=175%2C780%2C0.25&t=aTquhCUZ9MUh9tAk-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=2%3A6196

**Comment by saracampss** [comment]
Protótipo: https://www.figma.com/proto/kJgE4ThZiTpMIufCMTbbCI/Prot%C3%B3tipos?page-id=0%3A1&type=design&node-id=2-6196&viewport=-69%2C332%2C0.34&t=grIoU4CJLnRTRLcl-1&scaling=min-zoom&starting-point-node-id=2%3A6196&mode=design

**Comment by Mendonca-SINDPOL** [comment]
email e senha, poderia ser também por cpf o login? (email e cpf)

**Comment by Matheus-AM** [comment]
# Testes de aceitação 3
## Comportamento esperado
Dado que o usuário não se lembra de sua senha; Clicar em esqueci a senha; Preencher com o email que faz login; Verificar o email uma mensagem com o link para trocar de senha; Colocar a nova senha e confirmar; Acessar o login; Fazer o login com sucesso. 
## Comportamento observado
Dado que o usuário não se lembra de sua senha; Clicar em esqueci a senha; Preencher com o email que faz login; Verifiquei o email a mensagem com o link para trocar a senha; Fui redirecionado para a página de nova senha e preenchi; Fiz login com o novo email e senha.

## Observações
- Consegui criar um novo usuário, recebi a senha e loguei como o esperado.
- Consegui usar o "esqueci minha senha", recebi um email para mudar a senha e fiz login.

## Conclusão
Aceito. O login e o "esqueci minha senha" funcionaram com redirecionamento de email funcionando no ambiente de testes.
