### ISSUE TITLE
US02 - Solicitar filiação

### ISSUE THREAD

**Issue by saracampss** [fga-eps-mds/2024.1-SENTINELA-DOC#17]
### Descrição 
Eu como usuário inativo (não-filiado) gostaria de preencher formulário de filiação com os meus dados e assinar o Termo de Filiação e enviar o Termo de Filiação, para me filiar ao sindicato e me tornar um membro ativo.

#### Interface
- [x] Criação de interface do formulário de solicitar filiação;
- [x] A interface deve ser responsiva, suportando diferentes tamanhos de tela (desktop, tablet, mobile);
- [x] Campos pessoais de cadastro: nome completo, tipo sanguineo, matricula, data de nascimento, sexo,naturalidade, estado civil, escolaridade, RG, orgao expeditor, CPF, data expedição, nome do pai, nome da mãe, religião
- [x] Campos de contato: email, celular, telefone
- [x] Campos de endereço: cep, cidade, logradouro, complemento
- [x] Campos funcionais: cargo, data de admissão, lotação, orgão, posto de trabalho, status(Ativo, Inativo)
- [x] Adicionar dados de dependentes: nome completo, data de nascimento, parentesco, CPF, celular
- [x] Todos os campos de formulário deve estar presentes. 
- [x] O formulário precisa validar e limitar os dados antes de enviar (vide protótipo)
- [x] O usuário filiado deve esperar que o administrador do sistema aprove sua solicitação de filiação. Quando isso for feito, ele deve receber um e-mail de geração de senha para ativar sua conta. A US34 (Gerenciar filiação) complementa este fluxo com o lado do administrador que aprova ou rejeita a solicitação de filiação. O email de geração de senha é disparado portanto na US34 após aprovação da filiação.

#### Validação de campos
- [x] Campos obrigatórios: Nome, CPF, celular
- [x] Os campos - Sexo, UF, Status (Ativo, Inativo), Estado civil,cargo, lotação - devem ser selecionados por opções já definidas no sistema (sexo(feminino, masculino));
- [x] O campo CPF/CNPJ deve se adequar a quantidade de caracteres informados;
- [x] O campo CPF/CNPJ não deve aceitar valores não numéricos;
- [x] Exibir uma mensagem de erro "CPF/CNPJ inválido" se a validação falhar;
- [x] O campo email deve seguir o formato de email padrão (e.g., usuario@dominio.com);
- [x] O campo email deve conter um caractere "@" e um domínio válido (e.g., .com, .org, .net, etc.);
- [x] Caso o email não se encaixe no descrito anteriormente deve exibir uma mensagem de erro "Email inválido";
- [x] O valor inserido para celular/telefone deve seguir o formato padrão de números de telefone brasileiros (e.g., (##) ####-#### ou (##) #####-####);
- [x] Deve aceitar números de telefone fixo (10 dígitos) no seu campo específico quanto celular (11 dígitos) no seu campo específico;
- [x] O campo RG deve garantir que apenas números sejam inseridos.
- [x] Verificar se o número de RG tem o comprimento correto para o padrão do país (9 digitos)
- [x] Exibir uma mensagem de erro "Número de celular inválido" se a validação falhar;
- [x] Exibir uma mensagem de erro "Número de telefone inválido" se a validação falhar.

#### Funcionalidade de salvar (ao clicar no botão "Salvar")
- [x] O campo obrigatório deve ser validado;
- [x] Se todas as validações forem passadas, a solicitação de filiação deve ser enviada ao gestor;
- [x] Exibir uma mensagem de sucesso "Solicitação concluída";
- [x] Enviar link de definição de senha ao ser aprovada a solicitação.

### Tarefas
- [x] Criar protótipo da tela 
- [x] Enviar protótipo para validação do cliente
- [ ] Gerar código fonte responsivo conforme protótipo e critérios de aceitação
- [ ] Testes

### Protótipo
https://www.figma.com/proto/kJgE4ThZiTpMIufCMTbbCI/Prot%C3%B3tipos?page-id=0%3A1&node-id=2-6196&viewport=212%2C-274%2C0.15&t=VATvW1VkDk8olTQ0-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=2%3A6196

**Comment by ingridSCarvalho** [comment]
Protótipo navegável: https://www.figma.com/proto/kJgE4ThZiTpMIufCMTbbCI/Prot%C3%B3tipos?node-id=2-6267&t=Ir4amcWSSXsFxdRf-0&scaling=min-zoom&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=2%3A6196

**Comment by Mendonca-SINDPOL** [comment]
Se puder adicionar o campo de religião no formulário, o restante está ok

**Comment by Matheus-AM** [comment]
## Critérios
Fluxo esperado: (USUÁRIO NÃO FILIADO) formulario de filiação, preencher todos os dados, clicar em salvar, aceitar termo de compromisso; (USUÁRIO ADMIN) Acessar tela de solicitações de filiações, Aceitar a solicitação de filiação, enviar email para o usuário com a senha aleatória.
- Fiz o fluxo normal: fui para o formulario de filiação, preenchi todos os dados, cliquei em salvar, me apareceu o termo de compromisso, cliquei em "Aceito"... nada aconteceu (pode ser por conta do host. Vejo que as vezes o back-end "desliga" quando não está sendo usado)
## Bugs
### Campos de data
- Os campos de datas não funcionam se tenta preencher com o teclado (por exemplo: input "19111998" fica 01/11/0199)
- O pop-up de Data bugam quando se seleciona um ANO indo para o inicio da tela.
- Tem um campo "Situação atual" que agora usando, não parece fazer muito sentido estar no formulário. 
![Screenshot from 2024-08-08 13-09-32](https://github.com/user-attachments/assets/351ec440-a60d-4ae2-a626-8510fdca41d5)
![Screenshot from 2024-08-08 13-09-12](https://github.com/user-attachments/assets/ea18806a-721a-4524-8d2e-a80bfd20f25c)
### As validações 
- Não notei qualquer indicador como um "*"  que o campo é obrigatório.
- No geral não parecem estar funcionando
- Dilema do RG com CIN e DIN: o CPF se torna o novo RG (mais do que 9 números)
![Screenshot from 2024-08-08 13-07-44](https://github.com/user-attachments/assets/225c2935-3324-4f10-830c-05db82ccfe47)
### Problema de interface
- O fundo da tela não está como protótipo
- Ao clicar em adicionar dependentes, buga tudo, cria dois botões de enviar, e o texto vira "Adicionar Participantes"
- Nas telas não-desktop tá tudo bugado também (responsividade); (Possível solução: campos não-texto estão com os parâmetros de tela mobile errados)  
![Screenshot from 2024-08-08 13-11-36](https://github.com/user-attachments/assets/21a9ce23-6713-4678-b979-b75b41b8cf14)
![Screenshot from 2024-08-08 13-11-26](https://github.com/user-attachments/assets/393f20b1-e917-4285-afa6-389d4952e28f)
![Screenshot from 2024-08-08 13-29-30](https://github.com/user-attachments/assets/fd7bf8ca-207d-48ea-b9aa-2ecaaf0111ce)

**Comment by Mendonca-SINDPOL** [comment]
**DECLARAÇÃO DE FILIAÇÃO AO SINDPOL-DF**

Por meio desta, declaro que, ao filiar-me na presente data ao Sindicato dos Policiais Penais do Distrito Federal (SINDPOL-DF), estou plenamente ciente e de acordo com todas as obrigações previstas no Estatuto Social, no regime interno e nas deliberações das assembleias gerais do sindicato.

Comprometo-me a contribuir mensalmente com o valor equivalente a 1% do subsídio para os policiais penais ativos e 0,50% para aposentados e pensionistas, calculado com base no Padrão I da Terceira Classe da tabela de subsídio, conforme estabelece o Art. 105 do Estatuto, aprovado em assembleia geral. Autorizo que essa contribuição seja descontada em folha de pagamento junto ao órgão competente, em favor do SINDPOL-DF. Concordo também com a possibilidade de contribuições extraordinárias, desde que aprovadas em assembleia específica.

Reconheço que essas contribuições são fundamentais para manter a força e independência do sindicato, garantindo melhores condições de trabalho para toda a categoria.

Estou ciente de que, caso deseje solicitar meu desligamento do quadro de filiados do sindicato, devo fazê-lo por escrito, utilizando o formulário específico, com antecedência mínima de 60 (sessenta) dias.

Por meio desta, solicito formalmente minha admissão no quadro de filiados do SINDPOL-DF. Declaro, ainda, que todas as informações fornecidas nesta ficha estão protegidas pela Lei nº 13.709, de 14 de agosto de 2018 (Lei Geral de Proteção de Dados - LGPD).

**Comment by Mendonca-SINDPOL** [comment]
Se possível gostaria que alterasse a declaração de filiação

**Comment by Matheus-AM** [comment]
# Testes de aceitação (2a versão)
## Comportamento esperado
Preencher formulário de filiação, Ter feedback caso eu erre alguma coisa, Enviar o formulário, O admin aceitar o cadastro, Receber um email com o link para mudar a senha.
## Comportamento observado
Formulário foi preenchido, Foi dado feedback do que foi preenchido errado, Formulário foi enviado com sucesso, O admin recebeu para aceitar, O email não foi constatado ao aceitar no ambiente de teste (porem foi mandado um vídeo do email funcionando em AMBIENTE LOCAL)
## Observações
- Todos os critérios de aceitação que se referiam a "mensagem de ..." como por exemplo "Número de celular inválido" foram simplificadas como sendo "Ao falhar por conta de um campo, o usuário deve receber uma mensagem de feedback desse campo que falhou". Sendo assim por mais que não tenha acontecido os comportamentos de forma literal como nos critérios, foram aceitos.
- Por mais que tenha sido em ambiente local, foi aceito que, dado pelo o vídeo evidenciando, tendo um registro e email para encaminhar emails a parte de email está funcionando
- Bugs de data foram corrigidos
- A tela não parece responsível para celular, mas por mais que esteja responsível, é possível preencher os dados virando a tela o celular.
- Não sei se diz respeito a essa US02 ou à US34, mas o endereço na lista de pendencias não aparece.

**Comment by Matheus-AM** [comment]
# Teste de aceitação (3a versão)
Os ultimos critérios de aceitação que restaram foram: 
- Responsividade em telas mobile.
- E sobre os campos que deveriam já ser um select-box com opções.
## Observações
- A tela no celular os campos "UF" estavam levemente maiores que os outros campos (o que pode ser uma melhoria), mas o formulários está totalmente funcional, por isso considerei como aceito esse critério.
- Sobre os campos que deveriam auto-completar, todos os que seriam um ENUM estão funcionando e aceitei esse critério por isso. Porém diria que teriam outros campos (principalmente os dados de contratação) que precisariam de maior revisão e planejamento futuro, pois acredito que os dados como Cargo, Lotação, Orgão e Posto de Trabalho sejam ENTIDADES que não pensamos durante o planejamento inicial e agora parecem fazer sentido como ENTIDADES para poder fazer essa seleção. Então, na minha interpretação, acredito que seja necessário elucidar melhor essas ENTIDADES, CRUDs, etc... em novas US futuras para que seja possível manter coerência desses dados.
