### ISSUE TITLE
US03 - Cadastrar fornecedores

### ISSUE THREAD

**Issue by saracampss** [fga-eps-mds/2024.1-SENTINELA-DOC#18]
### Descrição 
Eu como GESTOR DO SINDICATO gostaria de gerenciar as informações sobre os fornecedores, portanto poder criar/atualizar/visualizar/deletar um fornecedor no sistema, para ter maior controle e manter o contato das parcerias e serviços favoráveis para o sindicato.

#### Interface de cadastro
- [x] Criação de interface do formulário de cadastro de fornecedores;
- [x] A interface deve ser responsiva, suportando diferentes tamanhos de tela (desktop, tablet, mobile);
- [x] Campo obrigatório do cadastro: Nome fantasia/Razão social;
- [x] Campos opcionais do cadastro: Classificação de pessoa (Jurídica, Física), CPF/CNPJ, Status (Ativo, Inativo), Natureza da transação (Receita, Despesa), E-mail, Nome do contato, Celular, Telefone, CEP, Cidade, UF, Logradouro, Complemento, Banco, Agência, Número, DV, Chave Pix.

#### Validação de campos
- [x] Os campos - Classificação de pessoa (Jurídica, Física), Status (Ativo, Inativo), Natureza da transação (Receita, Despesa), UF - devem ser selecionados por opções já definidas no sistema (ex.: Classificação de pessoa - Jurídica, Física);
- [x] O campo CPF/CNPJ deve se adequar a quantidade de caracteres informados;
- [x] O campo CPF/CNPJ não deve aceitar valores não numéricos;
- [x] Exibir uma mensagem de erro "CPF/CNPJ inválido" se a validação falhar;
- [x] O campo email deve seguir o formato de email padrão (e.g., usuario@dominio.com);
- [x] O campo email deve conter um caractere "@" e um domínio válido (e.g., .com, .org, .net, etc.);
- [x] Caso o email não se encaixe no descrito anteriormente deve exibir uma mensagem de erro "Email inválido";
- [x] O valor inserido para celular/telefone deve seguir o formato padrão de números de telefone brasileiros (e.g., (##) ####-#### ou (##) #####-####);
- [x] Deve aceitar números de telefone fixo (10 dígitos) no seu campo específico quanto celular (11 dígitos) no seu campo específico;
- [x] Exibir uma mensagem de erro "Número de celular inválido" se a validação falhar;
- [x] Exibir uma mensagem de erro "Número de telefone inválido" se a validação falhar.

#### Funcionalidade de salvar (ao clicar no botão "Salvar")
- [x] O campo obrigatório deve ser validado;
- [x] Se todas as validações forem passadas, o fornecedor cadastrado deve ser salvo no banco de dados;
- [x] Exibir uma mensagem de sucesso "Cadastro concluído";
- [x] Redirecionar o gestor para a lista de fornecedores cadastrados.

#### Deletar fornecedor
- [x] Exibir uma mensagem de confirmação antes de excluir;
- [x] Após a confirmação, o fornecedor deve ser removido do banco de dados;
- [x] Exibir uma mensagem de sucesso "Fornecedor excluído".

#### Atualizar dados de fornecedor
- [x] Ao acessar a edição, todos os campos devem ser preenchidos com os dados existentes;
- [x] Após a edição, as mesmas validações e mensagens de sucesso devem ser aplicadas.

#### Listar fornecedores
- [x] Exibir fornecedores cadastrados - Nome fantasia/Razão Social

### Tarefas
- [x] Criar protótipo da tela
- [x] Enviar protótipo para validação do cliente
- [x] Gerar código fonte responsivo conforme protótipo e critérios de aceitação
- [x] Testes

### Protótipo
https://www.figma.com/proto/kJgE4ThZiTpMIufCMTbbCI/Prot%C3%B3tipos?page-id=0%3A1&node-id=438-2684&viewport=-2565%2C-1651%2C0.31&t=mBZUgBc1zFnh3sfB-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=2%3A6196

Cadastro de Fornecedor: https://www.figma.com/proto/kJgE4ThZiTpMIufCMTbbCI/Prot%C3%B3tipos?page-id=0%3A1&node-id=249-2692&viewport=-2230%2C-938%2C0.31&t=w1CvLBmXYVfp0ym4-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=2%3A6196

Lista de Fornecedores: https://www.figma.com/proto/kJgE4ThZiTpMIufCMTbbCI/Prot%C3%B3tipos?page-id=0%3A1&node-id=615-2474&viewport=-2230%2C-938%2C0.31&t=w1CvLBmXYVfp0ym4-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=2%3A6196

Edição/Visualização de dados do Fornecedor: https://www.figma.com/proto/kJgE4ThZiTpMIufCMTbbCI/Prot%C3%B3tipos?page-id=0%3A1&node-id=914-2876&viewport=-2565%2C-1651%2C0.31&t=mBZUgBc1zFnh3sfB-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=2%3A6196

**Comment by annacbrandao** [comment]
**Cadastro de Usuário:** [https://www.figma.com/proto/kJgE4ThZiTpMIufCMTbbCI/Prot%C3%B3tipos?page-id=0%3A1&node-id=249-2692&viewport=-2230%2C-938%2C0.31&t=w1CvLBmXYVfp0ym4-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=2%3A6196](url)

**Lista de Fornecedores:** [https://www.figma.com/proto/kJgE4ThZiTpMIufCMTbbCI/Prot%C3%B3tipos?page-id=0%3A1&node-id=615-2474&viewport=-2230%2C-938%2C0.31&t=w1CvLBmXYVfp0ym4-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=2%3A6196](url)

**Edição de dados do Fornecedor:** [https://www.figma.com/proto/kJgE4ThZiTpMIufCMTbbCI/Prot%C3%B3tipos?page-id=0%3A1&node-id=388-1707&viewport=-2230%2C-938%2C0.31&t=w1CvLBmXYVfp0ym4-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=2%3A6196](url)

**Comment by Mendonca-SINDPOL** [comment]
aprovado

**Comment by Matheus-AM** [comment]
## Sobre o Teste de Aceitação da US03:
### Fluxo esperado
- cadastrar um novo fornecedor, Ver a lista de fornecedores, editar, deletar
### Resultados
- Tentei cadastrar um novo fornecedor, apareceu um pop-up de erro, apareceu uma mensagem de **"Cadastro de usuário concluído"** e voltou para lista de fornecedores em branco.
### Observações
- Não parece que os fornecedores estão sendo cadastrados, mas as telas estão ótimas, como estavam no protótipo
- Não vi nenhuma mensagem de erro de validação como "*Insira um email válido" no campo de email sem o formato correto.
- Não consegui editar ou deletar nada.

**Comment by Matheus-AM** [comment]
# Teste de aceitação 2
## Comportamento esperado
Dado que está logado, cadastrar um novo fornecedor, Ver a lista de fornecedores, editar, deletar
## Comportamento observado
Dado que estava logado, Consegui cadastrar um novo fornecedor, Verifiquei o novo fornecedor na lista de fornecedores, Editei-o, por fim o deletei.
## Observações
- Foi testado no formato desktop e mobile e o comportamento funcionou como esperado em ambos os formatos.
- O campo de UF parece um pouco fora do tamanho dos outros campos.
- Um detalhe que pode ter passado despercebido durante os critérios de aceitarção, mas os campos de Dados Bancários (agencia, numero, DV) estão aceitando valores não numéricos.

**Comment by Matheus-AM** [comment]
# Teste de aceitação 3
Os comportamento esperado foi observado, assim como o teste de aceitação 2.

## Observações
- Foi verificado a melhoria: os campos de Dados Bancários (agencia, numero, DV) pararam de aceitar valores não numéricos.
- O campo UF continua um pouco fora do tamanho dos outros campos no mobile.

**Comment by Matheus-AM** [comment]
# Teste de aceitação 4
## Observações
- O bug do tamanho do campo UF foi corrigido. Agora está no tamanho que deveria.
## Conclusão
Totalmente aceita. A US se comporta devidamente como o esperado e os bugs que apareceram foram corrigidos.
