### ISSUE TITLE
US05 - Cadastrar contas bancárias

### ISSUE THREAD

**Issue by saracampss** [fga-eps-mds/2024.1-SENTINELA-DOC#20]
### Descrição 
Eu como usuário gestor gostaria de registrar/atualizar/visualizar/deletar uma conta bancária no sistema, para gerenciar  as informações financeiras do sindicato.

### Critérios de aceitação
- [x] Interface do formulário de cadastro de contas bancárias
- [x] A interface deve ser responsiva, suportando diferentes tamanhos de tela (desktop, tablet, mobile).
- [x] Campos obrigatórios da conta: Tipo de conta (Conta Corrente, Poupança, Investimento, Caixa), Status (Ativo/Inativo), Banco, Nome
- [x] Campos opcionais da conta: Agência, Número Conta, DV, PIX

#### Validação de campos: 
- [x] Os campos - Tipo de conta e Status - devem estar em formato dropdown
- [x] Os campos - Agência e Numero Conta - devem se adequar a quantidade máxima de caracteres, 5 e 11 dígitos respectivamente. 
- [x] Os campos - Agência e Numero Conta - não devem aceitar valores não numéricos
- [x] Exibir uma mensagem de erro "Agencia/Conta inválida" se a validação falhar
- [x] O Campo DV é o dígito validador de Numero Conta
- [x] O Campo DV deve aceitar apenas 1 dígito de valores numérico

#### Funcionalidade de Salvar (ao clicar no botão "Salvar")
- [x] Todos os campos obrigatórios devem ser validados.
- [x] Se todas as validações forem passadas, a conta bancária alterada deve ser salva no banco de dados.
- [x] Exibir uma mensagem de sucesso "Conta bancária alterada".
- [x] Redirecionar o usuário para a lista de contas cadastradas.

#### Deletar conta
- [x] Exibir uma mensagem de confirmação antes de excluir.
- [x] Após a confirmação, a conta deve ser removida do banco de dados.
- [x] Exibir uma mensagem de sucesso "Conta deletada".

#### Atualizar benefício
- [x] Ao acessar a edição, todos os campos devem estar preenchidos com os dados existentes.
- [x] Após a edição, as validações e mensagens de sucesso devem ser aplicadas.

#### Listar benefícios
- [x] Exibir contas cadastrados pelo Nome

### Protótipo
https://www.figma.com/proto/kJgE4ThZiTpMIufCMTbbCI/Prot%C3%B3tipos?page-id=0%3A1&node-id=438-2684&viewport=254%2C-208%2C0.2&t=sycbhGdU6eW39eKw-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=2%3A6196

### Tarefas
- [x] Especificar critérios de aceitação
- [x] Criar protótipo da tela 
- [x] Enviar US e protótipo para validação do cliente
- [ ] Gerar código fonte responsivo conforme protótipo e critérios de aceitação
- [ ] Testes

**Comment by Mendonca-SINDPOL** [comment]
Poderia mudar o a seguencia no formulário para (nome, Tipo de conta, Banco, agência, número, dv, pix e status)

**Comment by ingridSCarvalho** [comment]
Modificações necessárias:
1. Rotas: Ao clicar em financeiro, deve redirecionar para o hub de financeiro e não para lista de fornecedores
2. Ajustar o intervalo de pixels que o responsivo não funciona
3. Incluir lista de contas bancárias
4. Remover o botão de Pesquisar e aplicar a pesquisa em tempo real

**Comment by Matheus-AM** [comment]
# Teste de aceitação
## Comportamento esperado
Dado que está logado no usuário administrador; ir para a página hub financeiro; ir para a página lista de contas bancárias;  Clicar em cadastrar contas bancárias; Preencher formulário de Conta bancária; clicar em salvar e confirmar; Verificar a conta bancária criada na lista de contas bancárias; clicar na nova conta bancária; Editar o nome e salvar; clicar novamente na nova conta bancária; clicar em deletar; Verificar se a conta sumiu da lista de contas bancárias.
## Comportamento observado
Dado que está logado no usuário administrador; fui para a página hub financeiro; fui para a página lista de contas bancárias; Cliquei em cadastrar contas bancárias; Preenchi formulário de Conta bancária; cliquei em salvar e confirmar; Verifiquei que a conta bancária criada na lista de contas bancárias; Cliquei na nova conta bancária; Editei o nome e salvei; cliquei novamente na nova conta bancária; cliquei em deletar; Verifiquei que a conta sumiu da lista de contas bancárias.
## Observações
- Fiz todo o fluxo na tela mobile e desktop, funcionou como o esperado. Validado.
- Verifiquei que na tela mobile os botões de confirmação tanto de deleção, quanto de criação estão sem espaçamento. O que não interfere no funcionamento da funcionalidade, mas poderia ser uma melhoria.
- Não é um comportamento esperado pelo usuário, mas durante a edição, as validações só ocorrem no back-end, podendo salvar um campo vazio (na interface); Aparece a mensagem de sucesso (na interface), mas no back-end essa consulta é negada mantendo o valor atual do compo obrigatório. Esse feedback no front-end poderia se tornar uma melhoria (por mais que seja não seja prioritário, visto que não faz parte do comportamento esperado do usuário)
