### ISSUE TITLE
US16 - Visualizar dashboard sobre os sindicalizados

### ISSUE THREAD

**Issue by saracampss** [fga-eps-mds/2024.1-SENTINELA-DOC#31]
### Descrição 
Eu como usuário gestor desejo visualizar um dashboard com informações sobre os sindicalizados para entender melhor o perfil dos membros do sistema

### Critérios de aceitação 
- [x] Usuário deve conseguir visualizar uma página com infográficos sobre os sindicalizados
- [x] Os infográficos devem estar sempre atualizados conforme os dados coletados do banco 
- [x] Os infográficos devem representar informações estatísticas reais sobre o sindicato/sindicalizados: Total de Filiados; Total de Filiações/Não Filiados; Filiados por situação (Ativo/Aposentado/Pensionista); Total de filiados por Lotação X Sexo (Feminino/Masculino)

### Tarefas
- [x] Especificar critérios de aceitação
- [x] Criar protótipo da tela 
- [x] Enviar US e protótipo para validação do cliente
- [x] Gerar código fonte responsivo conforme protótipo e critérios de aceitação
- [x] Testes

### Protótipo
https://www.figma.com/proto/kJgE4ThZiTpMIufCMTbbCI/Prot%C3%B3tipos?node-id=2323-5719&t=DcIi4MOFXKw4u2Hc-0&scaling=min-zoom&content-scaling=fixed&page-id=0%3A1

**Comment by Mendonca-SINDPOL** [comment]
Pode ser os seguintes:

Total de Filiados
Total de Filiações/Desfiliações/Não Filiados
Filiados por situação (Ativo/Aposentado/Pensionista
Total de filiados por Lotação X Sexo (Feminino/Masculino)

**Comment by Matheus-AM** [comment]
# Teste de aceitação
## Comportamento esperado 
Fazer login do usuário admin; acessar a área de dashboard; verificar os gráficos de inteligência de negócio atualizadas
## Comportamento observado
Fiz login com o usuário admin; fui redirecionado para a área de dashboard; verifiquei os gráficos e números de informação atualizadas. 
## Observações 
- Está validado. Consegui verificar o comportamento como esperado. 
- Sobre a continuidade do tópico sobre dashboard: o objetivo da área de dashboard é dar uma visão geral das informações mais estratégicas do negócio. No caso de um sindicato, por mais que tenha-se uma visão de negócio bem definida, os objetivos e estratégias são bem voláteis. É comum ter planejamentos mais táticos do que estratégicos. Dito isso, uma possível melhoria para a área de dashboard seria um pouco mais de versatilidade na escolha dos dados para que se adeque às necessidades de mudanças dos objetivos e das estratégias de negócio.
