### ISSUE TITLE
US19 - Cadastrar benefícios e convênios disponíveis

### ISSUE THREAD

**Issue by saracampss** [fga-eps-mds/2024.1-SENTINELA-DOC#34]
### Descrição 
Eu como usuário gestor gostaria de criar/atualizar/visualizar/deletar benefícios e convênios do sistema, para manter atualizados os benefícios e convênios disponibilizados pelo sindicato

#### Interface de cadastro
- [x] Criação de interface do formulário de cadastro de convênios
- [x] A interface deve ser responsiva, suportando diferentes tamanhos de tela (desktop, tablet, mobile).
- [x] Campos obrigatórios do convênio: Nome fantasia, Razão social, Status (Ativo, Inativo), Considerar no IR? (Sim, Não), Desconto automático? (Sim, Não)
- [x] Campos opcionais do convênio: categoria (Alimentação, Artes, Escolas, Academias, outros), logotipo, tipo de pessoa(Física/Jurídica), CPF/CNPJ, ANS, telefone/celular, e-mail, site, descrição, Data de cadastro
- [x] Campos opcionais do contrato de convênio: Data de assinatura, Data inicio, Data final, Contrato entregue? (Sim, Não), Situação (Concluído, Pendência, Cancelado)

#### Validação de campos: 
- [x] Os campos - Data de cadastro, Data de assinatura, Data início, Data final - devem estar em formato de data
- [x] Os campos - Data de cadastro, Data de assinatura, Data início, Data final não devem aceitar datas inválidas e não podem aceitar datas no passado exceto em caso de edição
- [x] O campo CPF/CNPJ deve se adequar a quantidade de caracteres informados
- [x] O campo CPF/CNPJ não deve aceitar valores não numéricos
- [x] Exibir uma mensagem de erro "CPF/CNPJ inválido" se a validação falhar
- [x] O campo email deve seguir o formato de email padrão (e.g., usuario@dominio.com), 
- [x] O campo email deve conter um caractere "@" e um domínio válido (e.g., .com, .org, .net, etc.)
- [x] Caso o email não se encaixe no descrito anteriormente deve exibir uma mensagem de erro "Email inválido".
- [x] O valor inserido para celular/telefone deve seguir o formato padrão de números de telefone brasileiros (e.g., (##) ####-#### ou (##) #####-####).
- [x] Deve aceitar tanto números de telefone fixo (10 dígitos) quanto celular (11 dígitos).
- [x] Exibir uma mensagem de erro "Número de telefone/celular inválido" se a validação falhar.
- [x] O campo site deve aceitar somente URL válida (e.g., http://www.exemplo.com/ ou https://www.exemplo.com/).
- [x] Exibir uma mensagem de erro "URL inválida" se a validação falhar.

#### Funcionalidade de Salvar (ao clicar no botão "Salvar")
- [x] Todos os campos obrigatórios devem ser validados.
- [x] Se todas as validações forem passadas, o benefício/convênio deve ser salvo no banco de dados.
- [x] Exibir uma mensagem de sucesso "Benefício/Convênio cadastrado com sucesso!".
- [x] Redirecionar o usuário para a lista de benefícios e convênios cadastrados.

#### Deletar convênio
- [x] Exibir uma mensagem de confirmação antes de excluir.
- [x] Após a confirmação, o benefício/convênio deve ser removido do banco de dados.
- [x] Exibir uma mensagem de sucesso "Benefício/Convênio excluído com sucesso!".

#### Atualizar convênio
- [x] Ao acessar a edição, todos os campos devem ser preenchidos com os dados existentes.
- [x] Após a edição, as mesmas validações e mensagens de sucesso devem ser aplicadas.

#### Listar convênio
- [x] Exibir convênios cadastrados - Nome fantasia

### Tarefas
- [x] Especificar critérios de aceitação
- [x] Criar protótipo da tela 
- [x] Enviar US e protótipo para validação do cliente
- [ ] Gerar código fonte responsivo conforme protótipo e critérios de aceitação
- [ ] Testes

### Protótipo
https://www.figma.com/proto/kJgE4ThZiTpMIufCMTbbCI/Prot%C3%B3tipos?page-id=0%3A1&node-id=1602-2973&viewport=-299%2C-2321%2C0.48&t=x1Ftaa7BWlRCb8kt-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=2%3A6196

**Comment by Mendonca-SINDPOL** [comment]
Aprovado

**Comment by Matheus-AM** [comment]
# Testes de aceitação
## Comportamento esperado
Clicar para cadastrar um beneficio, preencher os dados, verificar que os dados foram validados, benefício criado, lista de benefícios, editar um benefício, deletar um benefício. 
## Comportamento observado
Funcionou como o Comportament esperado, porém teve muitos problemas de carregamento e resposta (que parecem ser exclusivamente por conta hibernação do host de teste).
## Observações
- Todos os critérios de aceitação que se referiam a "mensagem de ..." como por exemplo "exibir mensagem de site inválido" foram simplificadas como sendo "Ao falhar por conta de um campo, o usuário deve receber uma mensagem de feedback desse campo que falhou". Sendo assim por mais que não tenha acontecido os comportamentos de forma literal como nos critérios, foram aceitos.
- Tiveram problemas de carregamento e resposta acima do normal o que me fez achar em uma primeira vez que não estava funcionando (demorou 10minutos até eu receber o feedback de que o beneficio foi criado e ele me retornar a lista de beneficios)
- Ao tentar editar o Nome Fantasia para vazio "" ele dá uma mensagem de sucesso, e volta o nome que estava antes.
