### ISSUE TITLE
US21 - Gerar relatório de movimentações financeiras 

### ISSUE THREAD

**Issue by saracampss** [fga-eps-mds/2024.1-SENTINELA-DOC#36]
### Descrição 
Eu como usuário gestor desejo exportar um PDF/CSV com relatório de movimentações financeiras para que eu possa analisar o fluxo de caixa e tomar decisões informadas sobre a gestão financeira do sindicato

### Critérios de aceitação 
- [x] O usuário deve conseguir solicitar um relatório do fluxo de caixa 
- [x] O usuário deve conseguir selecionar o período (Data Início e Data Fim) do qual deseja solicitar o relatório de fluxo de caixa
- [x] O usuário deve conseguir filtrar as movimentações financeiras que deseja ver no relatório (Conta Origem, Conta Destino, Tipo documento, Situação de pagamento)
- [x] O sistema deve gerar um PDF/CSV (conforme escolhido pelo usuário) com um relatório com uma lista das movimentações financeiras no período selecionado
- [x] O sistema deve fornecer a possibilidade de escolher os campos (tipo de documento, valor bruto, valor líquido, forma de pagamento, data de vencimento, data de pagamento, situação de pagamento e descrição) a serem exportados através de botões de seleção
- [x] A seção "filtro de geração" já deve vir, por padrão, preenchida. Quando o usuário gestor desmarcar algum campo, o mesmo não constará no relatório (csv/pdf)

### Tarefas
- [x] Especificar critérios de aceitação
- [x] Criar protótipo da tela 
- [ ] Enviar US e protótipo para validação do cliente
- [ ] Gerar código fonte responsivo conforme protótipo e critérios de aceitação
- [ ] Testes

Protótipo: https://www.figma.com/proto/kJgE4ThZiTpMIufCMTbbCI/Protótipos?node-id=438-2684&t=1Q8u3PcIMHbGZWqn-0&scaling=min-zoom&content-scaling=fixed&page-id=0%3A1

**Comment by Mendonca-SINDPOL** [comment]
Gerar relatório por:
Tipo de lançamento (Débito ou Crédito/Entrada ou Saída)
Fornecedor/Empresa
Tipo de documento (Advogado, energia, água, condominio, etc...)
Conta bancária (BRB, Mercado pago, etc...)
Situação de pagamento (pago ou não pago) 
Geral das movimentações
Data inicial, Data final
Formato arquivo (PDF, EXCEL ou CSV)

**Comment by Matheus-AM** [comment]
# Teste de aceitação
## Comportamento esperado
Dado que foi feito o login; Ir para a página de relatório financeiro; usar filtro de movimentações; Gerar relatório filtrado e verificar o documento filtrado;
## Comportamento observado
Fiz o login; Fui para a página de relatório financeiro; usei o filtro para selecionar os dado que achei relevantes; Gerei o documento; Verifiquei que estava com os valores selecionados pelo filtro.
## Observações
- Consegui gerar um pdf com os campos que eu queria sem problemas.
- Ao selecionar um filtro, Conta Origem por exemplo, não consegui mais desselecioná-lo sem ser recarregando a página.
## Conclusão
Aceito. Consegui gerar o relatório que a US tem como objetivo. Porém seria uma possível melhoria agradável poder desselecionar um filtro uma vez selecionado.
