### ISSUE TITLE
US33 - Atualizar dados de usuário 

### ISSUE THREAD

**Issue by saracampss** [fga-eps-mds/2024.1-SENTINELA-DOC#48]
### Descrição 
Eu como USUÁRIO SINDICALIZADO gostaria de atualizar meus dados no sistema, para manter meu cadastro atualizados

### Critérios de aceitação
- [x] Os dados já precisam vim preenchidos (Nome, e-mail, número de celular/telefone, status da conta, setores de acesso).
- [x] Botão de confirmação para atualizar os dados, com notificação de êxito.
- [x] Dados que não podem ser alterados (Nome, status da conta e setores de acesso).
- [x] Dados que podem ser alterados (Número de celular/telefone e  e-mail).
- [x] Não mostrar senha.

#### Validação de campos: 
- [x] O campo celular/telefone deve estar no formato (xx) xxxxx-xxxx ou (xx) xxxx-xxxx, contemplando tanto celular, como telefone fixo.
- [x] O campo celular/telefone deve aceitar tanto 10 dígitos, bem como 11 dígitos (2 DDD + 8 do número de telefone fixo ou 2 DDD + 9 do número de celular) para ser salvo. 
- [x] O campo celular/telefone não aceita letras, símbolos, ou caracteres especiais.
- [x] Exibir uma mensagem de erro "número inválido" se a validação falhar.
- [x] O campo email deve seguir o formato de email padrão (usuario@dominio.com/.org/.net etc.).
- [x] O campo email deve conter um caractere "@" e um domínio válido (.com, .org, .net, etc.).
- [x] Exibir uma mensagem de erro "email inválido" se a validação falhar.

### Tarefas
- [x] Criar protótipo da tela.
- [x] Enviar protótipo para validação do cliente.
- [ ] Gerar código fonte responsivo conforme protótipo e critérios de aceitação.
- [ ] Testes.

### Protótipo
https://www.figma.com/proto/kJgE4ThZiTpMIufCMTbbCI/Prot%C3%B3tipos?node-id=474-2690&t=obKVPMbc7JocTjvk-0&scaling=min-zoom&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=2%3A6196

**Comment by Mendonca-SINDPOL** [comment]
Aprovado

**Comment by Matheus-AM** [comment]
## Sobre o Teste de Aceitação da US33:
### Fluxo esperado
- Acessar o a página de visualização dos dados de usuário, editar dados, salvar
### Resultados
- Consegui acessar a página de dados do usuário, editei o telefone, salvei e constatei que mudou
### Observações
Critérios aceitos. Funcionou como esperado, mas após o uso levantou alguns questionamentos:
- Os emails pessoais no brasil são todos .com, .org, .net?
- O que acontece se eu mudar o Email (que concidentemente é o Login) de um usuário?
- E a senha so se muda no "Esqueci a senha"?
